name: Scrape and Update GitHub Pages

on:
  schedule:
    - cron: '0 * * * *'  # Runs every minute for testing, change to daily or as needed
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # Allow GitHub Actions bot to push changes

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use Node.js 18 (required for Cheerio dependencies)

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install axios cheerio puppeteer

      # Step 4: Run the scraping script
      - name: Run scraping script
        run: node scrape.js

      # Step 5: Configure Git
      - name: Configure Git
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      # Step 6: Commit and push changes to GitHub Pages branch
      - name: Commit and push changes
        run: |
          git add data.json
          git commit -m "Update flight data" || echo "No changes to commit"
          git push
